config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages

  root "pages#index"

end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  has_many :pages, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_action :find_page, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pages = Page.all.order("created_at DESC")
	end

	def show
	end

	def new
		@page = current_user.pages.build
	end

	def create
		@page = current_user.pages.build(page_params)

		if @page.save
			redirect_to @page
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @page.update(page_params)
			redirect_to @page
		else
			render 'edit'
		end
	end

	def destroy
		@page.destroy
		redirect_to root_path
	end

	private

	def page_params
		params.require(:page).permit(:name)
	end

	def find_page
		@page = Page.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!

%html
%head
	%title Blokks
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body

	.navbar.navbar-inverse.navbar
		.container
			.navbar-header
				= link_to "All Pages", root_path, class: "navbar-brand"
			
			.navbar-right
				- if user_signed_in?
					= link_to "Create Page" , new_page_path, class: "navbar-brand"
					= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-brand"
					= link_to "Edit Account", edit_user_registration_path, class: "navbar-brand"
				- else
					= link_to "Sign Up", new_user_registration_path, class: "navbar-brand"
					= link_to "Sign In", new_user_session_path, class: "navbar-brand"

	.container
		%p.notice= notice
		%p.alert= alert

		= yield

app/views/pages/_form.html.haml
= simple_form_for @page do |form|
	= form.input :name

	= form.button :submit

app/views/pages/edit.html.haml
%h2 Edit Page

= render 'form'

app/views/pages/index.html.haml
%h1 Blokks
%hr

- @pages.each do |page|
	%h2= link_to page.name, page
	%p
		Shared by
		= page.user.name
		= time_ago_in_words(page.created_at)
		ago
	%hr

app/views/pages/new.html.haml
%h2 New Page

= render 'form'

app/views/pages/show.html.haml
%h2= @page.name

- if user_signed_in? && @page.user == current_user
	= link_to "Edit", edit_page_path(@page), class: "btn btn-default"
	= link_to "Delete", page_path(@page), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"